### ISSUE TITLE
Service Layer Base

### ISSUE THREAD

**Issue by OhCaesar** [OhCaesar/SchoolDemo#3]
### FeatureType

Technical Feature

### Is this feature optional?

- [ ] Optional

## Description
Structure the Service layer

## Tasks
- [ ] Functional Service Layer - Working Service Classes that are successfully wired to each repo class 
- [ ] Correct Logging for each method/ Transaction
- [ ] Unittests

### Do you need any extra dependencies?

- [ ] I do need extra dependencies
